### ISSUE TITLE
Library is not compatible with AndroidX Projects

### ISSUE THREAD

**Issue by pawsaw** [samitha9125/react-native-pinch-new#1]
Due to this line of code :

https://github.com/samitha9125/react-native-pinch-new/blob/c015ab24675379d8eb2a38d46bbb89204ad8bc2a/android/src/main/java/com/localz/RNPinch.java#L4

`./gradlew assembleRelease` on the main project fails.

**Comment by IsuruSathyajith** [comment]
What's the react-native version you are using?
Have you tried using jetifier?? 
https://stackoverflow.com/questions/56667264/react-native-build-error-package-android-support-annotation-does-not-exist

**Comment by samitha9125** [comment]
As isuru said you need to verify you are using jetifier. If not or if you are not sure, please follow this answer from stackoverflow.

**Comment by pawsaw** [comment]
Hi. Thank you for your help. I tried a couple of approaches, none of them actually helped. I'm aware of jetifier as well as `npx jetify`.

I've been successful with this settings (build.gradle):

https://github.com/pawsaw/react-native-pinch-new/blob/master/android/build.gradle

**Comment by samitha9125** [comment]
Good to know. Since you resolved your issue, I’m gonna close this.
