### ISSUE TITLE
Unhandled promise rejection reactNativePinchNew.default - Android

### ISSUE THREAD

**Issue by ghena** [samitha9125/react-native-pinch-new#2]
Hi guys,

I'm trying with expo to apply this kinfd of solution but it doesnt work:

[Unhandled promise rejection: TypeError: Object is not a function (near '...(0, _reactNativePinchNew.default)...')]

I put my certificate inside the root folder of react native project

\myapp\src\main\assets\mycert.cer

then i try to consume my page:

 pinch('myurl', {
    method: "POST" ,
    timeoutInterval: 10000, // milliseconds
    body: {},
    // your certificates array (needed only in android) ios will pick it automatically
    sslPinning: {
      certs: ["mycert"]
    },
    headers: {
      Accept: "application/json; charset=utf-8", "Access-Control-Allow-Origin": "*",
    }
  }).then(response => {
    console.log(`response received ${response}`)
  })
  .catch(err => {
    console.log(`error: ${err}`)
  });
   
this is my error:

[Unhandled promise rejection: TypeError: Object is not a function (near '...(0, _reactNativePinchNew.default)...')]
* screens\HomeScreen.js:82:14 in componentDidMount
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:271:30 in invoke
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:135:28 in invoke
- node_modules\regenerator-runtime\runtime.js:145:19 in Promise.resolve.then$argument_0
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:194:17 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:407:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

**Comment by samitha9125** [comment]
Can you kindly try this on a new expo project and if this issue still exists, share the repo with me? Then I can provide a solution asap.

**Comment by samitha9125** [comment]
Going to close this because of no response.
