### ISSUE TITLE
axions support?

### ISSUE THREAD

**Issue by ahmetozalp** [samitha9125/react-native-pinch-new#8]
hello,

can i use this package axions too?

**Comment by samitha9125** [comment]
@ahmetozalp What do you mean?

**Comment by ahmetozalp** [comment]
Can I use this on the axions package?

**Comment by samitha9125** [comment]
@ahmetozalp This is not an extension. So you cannot use this combined with axios but obviously both of them will work separately even in the same project.

**Comment by ahmetozalp** [comment]
I installed, run this Add-on, I can still see traffic with wireshark

**Comment by samitha9125** [comment]
@ahmetozalp can you please clarify what you want to do? With some code sample?
