### ISSUE TITLE
Support for Public Key Pinning

### ISSUE THREAD

**Issue by ronandowlingcullen** [samitha9125/react-native-pinch-new#9]
Great Library! Are you looking to support public key pinning any time soon?

**Comment by samitha9125** [comment]
@ronandowlingcullen We are not going to support public key pinning since it is a deprecated security mechanism. I’m sorry. Btw thank you for using this library.

**Comment by ronandowlingcullen** [comment]
Hi @samitha9125 thanks for getting back to me so quickly
